# Base configs
baseurl: ""
url: "thebig-o.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-98381528-1"

# UI configs
title: "Photography by Mike Olness"
subtitle: "See the world through my eyes!"
author: "Mike Olness"
bio: "I am a photographer and a tech aficionado. I Love photography and teeny tiny apps to solve tiny problems in life."
#publicise: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/molness"
  twitter: "https://www.twitter.com/major_o"
  instagram: "https://www.instagram.com/mfolness_photos"
  dribbble: ""
  linkedin: "https://in.linkedin.com/in/mikeolness"
  github: "https://www.github.com/TheBig-O"
  
theme: jekyll-theme-tactile
